# SimpleLinks v3 by Refrac
#--------------------------------------
# Placeholders: (PlaceholderAPI is supported)
# %player% - Get the player name
# %displayname% - Get the player display name
# %arrow% - Get an arrow for a message
# %arrow_2% - Get alt arrow for a message
# %star% - Get a star for a message
# %circle% - Get a circle for a message
# %empty% - Disable any message with this placeholder
#--------------------------------------
messages:
  no-permission: "&cYou don't have permission to execute this command."
  reload: "&eConfig files reloaded. Changes should be live in-game!"

# This sends on /links if the menu is disabled
links:
  - "&7&m----------------------------------------------------"
  - ""
  - "&eWebsite: &dhttps://yourserver.net"
  - "&eDiscord: &dhttps://discord.gg/yourservercode"
  - "&eStore: &dhttps://store.yourserver.net"
  - "&eTwitter: &dhttps://twitter.com/yourserver"
  - ""
  - "&7&m----------------------------------------------------"

menu:
  enabled: true
    title: "&dServer Links"
    size: 54
    fill:
      material: STAINED_GLASS_PANE
      data: 15
      name: "&7"
      lore:
        - ""
    # Infinite items can be added or removed
    items:
      website:
        material: DOUBLE_PLANT
        data: 0
        name: "&eWebsite"
        lore:
          - "&7Click to receive a link to the website."
        slot: 10
      discord:
        material: DOUBLE_PLANT
        data: 0
        name: "&eDiscord"
        lore:
          - "&7Click to receive a link to the discord."
        message: "&eDiscord: &dhttps://discord.gg/yourservercode"
        slot: 12
      store:
        material: DOUBLE_PLANT
        data: 0
        name: "&eStore"
        lore:
          - "&7Click to receive a link to the store."
        message: "&eStore: &dhttps://store.yourserver.net"
        slot: 14
      twitter:
        material: DOUBLE_PLANT
        data: 0
        name: "&eTwitter"
        lore:
          - "&7Click to receive a link to the twitter."
        message: "&eTwitter: &dhttps://twitter.com/yourserver"
        slot: 15