name: 'SimpleLinks'
version: '${project.version}'
main: me.refrac.simplelinks.SimpleLinks
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - Skulls
author: 'Refrac'
description: 'A simple links plugin'
website: 'https://discord.gg/EFeSKPg739'

commands:
  links:
    description: 'Links command'
  linksreload:
    description: 'Reload Command'