name: SimpleLinks
version: '@version@'
main: me.refracdevelopment.simplelinks.SimpleLinks
author: RefracDevelopment
api-version: "1.13"
depend:
  - PlaceholderAPI
softdepend:
  - Skulls
  - HeadDatabase
description: A simple links plugin
website: https://discord.refracdev.ml/

permissions:
  simplelinks.*:
    description: Gives access to all SimpleLinks commands
    children:
      simplelinks.command.reload: true
      simplelinks.command.version: true
  simplelinks.command.reload:
    description: Gives access to the reload command
    default: op
  simplelinks.command.version:
    description: Gives access to the version command
    default: op